version: '3.8'

services:
  core-backend:
    build: 
      context: ./services/core-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URL=postgres://user:pass@postgres:5432/gigshield
      - REDIS_URL=redis://redis:6379
      - ML_SERVICE_URL=http://ml-fraud-engine:8000
    depends_on:
      - postgres
      - redis
      - ml-fraud-engine

  ml-fraud-engine:
    build:
      context: ./services/ml-fraud-engine
    ports:
      - "8000:8000"
    depends_on:
      - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gigshield
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

networks:
  default:
    name: gigshield-network
